version: "3"
services:
  api:
    build: .
    environment:
      - DATABASE_HOST=mongo
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
  web-app:
    build: webapp
    ports:
      - "5000:80"
    depends_on:
      - api
    restart: unless-stopped